artist:
  name: Drum Nico
  tagline: Percussionist Nico Spezzacatena
  # seo_title:
  # seo_description:
  # contact_twitter_username:
  # contact_phone: 
  # contact_email: 

social:
  - name: Facebook
    url: https://www.facebook.com/nico.spezzacatena

site_language: en
