artist:
  name: Nico Spezzacatena
  tagline: Drum in the Sun with Nico
  seo_title: Drum in the Sun with percssionist Nico Spezzacatena
  seo_description: tabla, ewe, arfican, drum, instruction, teacher
  contact_phone: 661-312-3924
  contact_email: drumnico@hotmail.com

social:
  - name: Facebook
    url: https://www.facebook.com/nico.spezzacatena

site_language: en
