navigation:
  - text: About
    url: "#about"
  - text: Workshops
    url: "#workshops"
  - text: For Sale
    url: "#forsale"
  - text: Videos
    url: "#videos"
  - text: Contact
    url: "#contact"
